### ISSUE TITLE
Migrate To Gitlab

### ISSUE THREAD

**Issue by windlessuser** [P3GLEG/WhaleTail#2]
With the sale of GitHub to Microsoft, this project is no longer safe here. Please migrate the project and it’s connu over to GitLab where they still believe in Open Source.

Thank you

**Comment by P3GLEG** [comment]
Well, I understand where you are coming from. I think a lot of OSS developers are wondering what is going on in the world. However, the project is safe. It is open source and available to the world. What could Microsoft do to it that hasn't already been done? They can't claim this project as their own. There are much more interesting ones, like React or NodeJS. They won't just suddenly say NodeJS belongs to Microsoft now, that would be the worst thing they could do for their business. That isn't how it works. Who is to say GitLab won't be taken over by Google, Apple or any other big company in the future? I think the concern comes into play for private repositories where intellectual property could be viewed/stolen before it's released. However, that is something not related to the project and something we could discuss over a coffee/beer.

Cheers,
Pegleg
